services:
  pg5:
    image: postgres:14.18-bullseye
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - "5555:5432" # Simply so I can use pgAdmin on my local machine to get access to the database

  app:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - "$PWD/.env"

    ports:
      - "3000:3000"

    depends_on:
      - pg5

volumes:
  postgres_volume:
